# Generated by Django 4.1.8 on 2023-08-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("published_date", models.DateField()),
                ("isbn_number", models.CharField(max_length=13, unique=True)),
                ("page_count", models.PositiveIntegerField()),
                ("language", models.CharField(max_length=20)),
            ],
        ),
    ]
